Fallback implementations for GHCjs
blamario/monoid-subclasses pull request #32
Opened 2021-10-29 22:08 UTC by endgame

The internal representation of `Text` is different on GHCjs, so provide a slower fallback.

2021-10-30 19:42 UTC, blamario requested changes
Is this the *only* change needed for GHCjs?

Also note that it would probably be faster to use `ByteString` rather than `String` as the intermediate format, if GHCjs supports conversion of `Text` to and from UTF-8 encoded `ByteString`. Can you do that instead?

2021-10-30 21:18 UTC, endgame commented
> Is this the only change needed for GHCjs?

Yes: I am using this branch in https://git.sr.ht/~jack/casaaaaa , and it works: https://git.sr.ht/~jack/casaaaaa/tree/b0dddd9d658eb74c998e3e38db4d1e7dea61eaed/item/flake.nix#L43-51

> Can you [use `ByteString`] instead?

Yes; pushed.

2021-10-31 15:03 UTC, blamario approved these changes

2021-10-31 15:04 UTC, merged

2021-10-31 15:04 UTC, blamario commented
Thank you.